version: '3'
services:
  nextjs:
    build: ./
    restart: unless-stopped
    env_file:
      .env
    networks:
      - proxy-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-network"
      - "traefik.http.routers.nextjs-frontend.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.nextjs-frontend.entrypoints=websecure"
      - "traefik.http.routers.nextjs-frontend.tls=true"
      - "traefik.http.services.nextjs-frontend.loadbalancer.server.port=${PORT}"

networks:
  proxy-network:
    external: true