version: '3'
services:
  nextjs:
    build: ./
    restart: unless-stopped
    env_file:
      .env
  nginx:
    build: ./nginx
    depends_on:
      - nextjs
    restart: unless-stopped
    ports:
      - 10443:443
