export const ADMIN_ENDPOINTS = {
  USERS: "/admin/users",
  USER_ACTIVATE: "/admin/users/activate",
  USER_DEACTIVATE: "/admin/users/deactivate",
  ORIGINS: "/admin/origins",
  ORIGINS_SEARCH: "/admin/origins/search?name=",
  SEQUENCERS: "/admin/sequencers",
  SEQUENCERS_SEARCH: "/admin/sequencers/search?brandOrModel=",
  SAMPLE_SOURCES: "/admin/sample-sources",
  SAMPLE_SOURCES_SEARCH: "/admin/sample-sources/search?nameOrGroup=",
  LABORATORIES: "/admin/laboratories",
  LABORATORIES_SEARCH: "/admin/laboratories/search?nameOrAbbreaviation=",
  MICROORGANISMS: "/admin/microorganisms",
  MICROORGANISMS_SEARCH: "/admin/microorganisms/search?species=",
  HEALTH_SERVICES: "/admin/health-services",
  HEALTH_SERVICES_SEARCH: "/admin/health-services/search?name=",
  SAMPLES: "/admin/samples",
  SAMPLES_SEARCH: "/admin/samples/search",
  ANALYSES: "/admin/analyses",
  ANALYSES_SEARCH: "/admin/analyses/search",
  TICKETS: "/admin/tickets",
} as const;
