const en = {
  Menu: {
    home: "Home",
    network: "Network",
    dashboard: "Dashboard",
    about: "About",
    contact: "Contact",
    login: "Login",
  },
  Home: {
    Banner: {
      bannerTitle: "CABGen: Clinical Applied Bacterial Genomics",
    },
    CabgenDescription: {
      description:
        "Digital platform that integrates tools for bacterial genomic sequencing data analysis, capable of organizing, storing, and providing results obtained through efficient visualization methods.",
      articleBtn: "Article",
    },
    Statistics: {
      sectionTitle: "CABGen in Numbers:",
      sectionSubtitle: "Statistics and Impact",
      sectionDescription:
        "Since its launch, CABGen has attracted increasing interest, with a significant number of submitted genomes, addressing a variety of bacterial species. Several acquired resistance genes have already been identified. CABGen has received contributions from different countries, reflecting its collaborative and global nature. These preliminary statistics highlight the potential of CABGen to drive advances in genomic research and public health, providing a solid foundation for future discoveries.",
      loginBtn: "Start",
    },
    BoxInfo: {
      genomesInfo: "submitted genomes",
      speciesInfo: "analyzed species",
      genesInfo: "detected resistance genes",
      countriesInfo: "submitting countries",
    },
    GenomicSurveillance: {
      sectionTitle: "NATIONAL GENOMIC SURVEILLANCE NETWORK OF",
      sectionSubtitle: "MULTIDRUG-RESISTANT BACTERIA IN BRAZIL",
      sectionDescription:
        "Network that integrates Brazilian laboratories for genomic sequencing of carbapenemase-producing bacteria to obtain relevant information for controlling the spread of these microorganisms.",
      learMoreBtn: "Learn More",
    },
    AntimicrobialResistance: {
      sectionTitle: "What is",
      sectionSubtitle: "Antimicrobial Resistance ?",
      sectionDescription:
        "Antimicrobial resistance (AMR) represents a global threat to the effectiveness of treatments for infections caused by microorganisms such as viruses, bacteria, fungi, and parasites. This resistance arises when these microorganisms undergo mutations or acquire new genes that make them resistant to treatment. Prevalent bacterial pathogens in hospitals have alarming rates of resistance, prolonging infections, increasing the risk of spread, and hospital costs. This scenario requires joint action from all sectors of society and government. AMR knows no borders and affects not only human health but also animal health, agricultural productivity, and food security.",
      omsBtn: "WHO",
      nationalPlanBtn: "National Plan",
    },
    Financiers: {
      sectionTitle: "Financiers",
    },
  },
  Network: {
    Description: {
      firstParagraph:
        "The network brings together experts in antimicrobial resistance (AMR) and bioinformatics from different units of Fiocruz, LACEN, and CGLAB-MS, with a main focus on structuring, training, analysis, and interpretation of whole genome sequencing data from multidrug-resistant bacteria. This initiative will allow for a deeper understanding of the AMR scenario in Brazil, with the intention of ensuring agility for future actions in controlling the spread of these microorganisms.",
      secondParagraph:
        "Each laboratory participating in the network conducts sequencing independently, and the analysis of the generated data is standardized and automated through CABGen. The information generated by the network members is available visually and interactively in CABGen, allowing for communication of the results to the scientific community and healthcare professionals.",
      thirdParagraphFirstPart:
        "The initial focus of the network is the study of species of multidrug-resistant gram-negative bacilli",
      thirdParagraphSecondPart:
        "Pseudomonas aeruginosa, Acinetobacter baumannii, and Klebsiella pneumoniae",
      thirdParagraphThirdPart:
        ", producers of carbapenemases. These samples are included in the Collection of Hospital-Origin Bacterial Cultures (CCBH/IOC - WDCM 947), for preservation of bacterial cultures. In addition, genomic data is protected on its own server hosted at Fiocruz/RJ, in a certified safe room according to NBR 15247. The network is open for formalization of new partners. If interested, please contact.",
      contactBtn: "Contact",
      dashboardBtn: "Dashboard",
    },
    Map: {
      sectionTitle: "Current Members",
    },
  },
  Dashboard: {
    sectionTitle: "Genomic Network Data",
  },
  About: {
    CabgenMission: {
      sectionTitle: "Understand ",
      sectionSubtitle: "Mission and Purpose",
      sectionDescriptionFirstParagraph:
        "CABGen emerges as a solution to the challenges faced with the exponential increase in data generated by genomic sequencing of antimicrobial-resistant bacteria (AMR). In response to the urgency to combat AMR and bridge the gap between generation and analysis of genomic data, CABGen offers essential functionalities such as species identification, detection of resistance-related genes and mutations, assignment of a clonal profile, and verification of plasmid existence. These tools simplify and enhance the analysis and interpretation of biological data, providing valuable insights for clinical applications.",
      sectionDescriptionSecondParagraph:
        "Furthermore, the system is constantly evolving to meet growing demands, with plans for the installation of a new server that will allow up to 60 parallel analyses, as well as robust storage capable of supporting up to 120,000 samples. The security of CABGen is ensured by both the firewall of the Programa de Computação Científica (PROCC) network and Fiocruz's rigorous security policies.",
      articleBtn: "Article",
    },
    CabgenPipeline: {
      sectionTitle: "Inside ",
    },
    CabgenResults: {
      sectionTitle: " results",
    },
    Team: {
      sectionTitle: "Meet our Professionals",
      roleAnaPaula:
        "Responsible for coordinating the project, analyzing phenotypic, molecular, and sequencing results, and sending the results to the Laboratory Environment Management System (GAL).",
      roleFabricio:
        "Responsible for managing the use of the Fiocruz server for genome assembly and database development for genome availability.",
      roleFelicita:
        "Ph.D. student in the Computational Biology and Systems Program of the Doctorate in Health Sciences International cooperation between Fundação Oswaldo Cruz and Focem-Mercosur - Paraguay.",
      roleMelise:
        "Responsible for analyzing the results obtained in whole genome sequencing.",
      roleRodolpho: "Researcher at UERJ.",
      roleClaudio:
        "Responsible for managing the laboratory activities of LAPIH and lyophilization and storage of bacterial samples.",
      roleNicolas:
        "Responsible for the development of the new version of CABGen's front-end.",
    },
    AboutContact: {
      sectionTitle: "Want to know more? Contact us!",
      sectionDescription:
        "If you have any questions, we're here to help. Visit our contact page to learn how to use our tool. Fill out the form or contact us via email.",
      contactBtn: "Contact",
    },
  },
  Contact: {
    formSubtitle: "Please leave your message, question, or suggestion.",
    nameField: "Name",
    nameFieldValidation: "Name is required.",
    emailField: "Email",
    emailFieldValidationNull: "Email is required.",
    emailFieldValidationValid: "Please enter a valid email.",
    institutionField: "Institution",
    institutionFieldValidation: "Institution is required.",
    subjectField: "Subject",
    subjectFieldValidation: "Subject is required.",
    messageField: "Message",
    messageFieldValidation: "Message is required.",
    sendBtn: "Send",
  },
  Login: {
    usernameField: "Username",
    usernameFieldValidation: "Username is required.",
    passwordField: "Password",
    passwordFieldValidation: "Password is required.",
    loginBtn: "Continue",
    formFooter1: "Don't have an account? ",
    formFooter2: "Sign up.",
  },
  Register: {
    nameField: "Name",
    nameFieldValidation: "Name is required.",
    countryField: "Country",
    countryFieldLabel: "Select a Country",
    countryFieldValidation: "Country is required.",
    usernameField: "Username",
    usernameFieldValidation: "Username is required.",
    interestField: "Interest",
    institutionField: "Institution",
    roleField: "Role",
    emailField: "Email",
    emailFieldValidationNull: "Email is required",
    emailFieldValidationValid: "Please enter a valid email.",
    confirmEmailField: "Confirm Email",
    confirmEmailFieldValidationNull: "Confirm email is required.",
    confirmEmailFieldValidationValid: "Please enter a valid email.",
    passwordField: "Password",
    passwordFieldValidationNull: "Password is required.",
    passwordFieldValidationMinimum: "Password needs at least 8 characters.",
    confirmPasswordField: "Confirm Password",
    confirmPasswordFieldValidation: "Confirm password is required.",
    bothEmailFieldsValidation: "Emails do not match.",
    bothPasswordFieldsValidation: "Passwords do not match.",
    registerBtn: "Continue",
    formFooter1: "Already have an account? ",
    formFooter2: "Log in.",
  },
  Footer: {
    faqLink: "FAQ",
    termLink: "Terms of Use",
    imageCredits: "Image Credit",
  },
};

export default en;
